WebMarathon/Models/Travel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebMarathon.Models
{
    public class Travel
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Клієнт")]
        public string UserId { get; set; }
        [ForeignKey("UserId")]
        public virtual ApplicationUser User { get; set; }

        [Required]
        [Display(Name = "Туристична пам'ятка")]
        public int MonumentId { get; set; }
        public WorldMonument Monument { get; set; }

        [Required]
        [Display(Name = "Дата подорожі")]
        public DateTime Date { get; set; }

        [Required]
        [Display(Name = "Статус")]
        public string Status { get; set; }
    }
}

WebMarathon/Controllers/TravelController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;
using WebMarathon.Models;

namespace WebMarathon.Controllers
{
    public class TravelController : Controller
    {
        private readonly ApplicationDbContext _db;
        UserManager<ApplicationUser> _userManager;

        public TravelController(ApplicationDbContext db, UserManager<ApplicationUser> userManager)
        {
            _db = db;
            _userManager = userManager;
        }

        public IEnumerable<Travel> GetTravels()
        {
            //для виводу створених заявок поточного користувача
            //var travels = (from travel in _db.Travels
            //             join monument in _db.WorldMonuments on travel.MonumentId equals monument.Id
            //             join users in _db.Users.Where(u => u.Id == _userManager.GetUserId(HttpContext.User)) on travel.UserId equals users.Id
            //             select new Travel
            //             {
            //                 Id = travel.Id,
            //                 UserId = travel.UserId,
            //                 MonumentId = travel.MonumentId,
            //                 Date = travel.Date,
            //                 Status = travel.Status
            //             }
            //             ).ToList();

            var travels = (from travel in _db.Travels
                           join monument in _db.WorldMonuments on travel.MonumentId equals monument.Id
                           join users in _db.Users on travel.UserId equals users.Id
                           select new Travel
                           {
                               Id = travel.Id,
                               UserId = travel.UserId,
                               MonumentId = travel.MonumentId,
                               Date = travel.Date,
                               Status = travel.Status
                           }
                         ).ToList();

            return travels;
        }

        public IActionResult TravelIndex()
        {
            IEnumerable<Travel> objList = GetTravels();
            foreach (var obj in objList)
            {
                obj.Monument = _db.WorldMonuments.FirstOrDefault(u => u.Id == obj.MonumentId);
                obj.User = _db.Users.FirstOrDefault(u => u.Id == obj.UserId);
            }
            return View(objList);
        }

        // GET-Create
        public IActionResult TravelCreate()
        {
            IEnumerable<SelectListItem> TravelDropDown = _db.WorldMonuments.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });

            ViewBag.TravelDropDown = TravelDropDown;

            return View();
        }

        // POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult TravelCreate(Travel model)
        {

            var travel = new Travel
            {
                UserId = _userManager.GetUserId(HttpContext.User),
                MonumentId = model.MonumentId,
                Date = model.Date,
                Status = model.Status,
            };

            _db.Travels.Add(travel);
            _db.SaveChanges();
            return RedirectToAction("TravelIndex");
        }
        // GET Update
        public IActionResult TravelUpdate(int? id)
        {
            IEnumerable<SelectListItem> TravelDropDown = _db.WorldMonuments.Select(i => new SelectListItem
            {
                Text = i.Name,
                Value = i.Id.ToString()
            });

            ViewBag.TravelDropDown = TravelDropDown;

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var travel = _db.Travels.Find(id);
            if (travel == null)
            {
                return NotFound();
            }
            return View(travel);

        }

        // POST UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult TravelUpdate(Travel model)
        {
            model.UserId = _userManager.GetUserId(HttpContext.User);
            _db.Travels.Update(model);
            _db.SaveChanges();
            return RedirectToAction("TravelIndex");
        }

    }
}

WebMarathon/Controllers/WorldMonumentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMarathon.Models;

namespace WebMarathon.Controllers
{
    public class WorldMonumentController : Controller
    {

        private readonly ApplicationDbContext _db;

        public WorldMonumentController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult MonumentIndex()
        {
            IEnumerable<WorldMonument> objList = _db.WorldMonuments;

            return View(objList);
        }
    }
}

WebMarathon/Views/Travel/TravelCreate.cshtml
@model WebMarathon.Models.Travel

<form method="post" asp-action="TravelCreate">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Додати тур</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label>Користувач</label>
                    </div>
                    <div class="col-4">
                        <label asp-for="MonumentId"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Date"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label>@User.Identity.Name</label>
                    </div>
                    <div class="col-4">
                        <select asp-for="MonumentId" asp-items="@ViewBag.TravelDropDown" class="form-control"></select>
                        <span asp-validation-for="MonumentId" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Date" class="form-control" />
                        <span asp-validation-for="Date" class="text-danger"></span>

                    </div>
                    <div class="col-3">
                        <input asp-for="Status" value="@WebMarathon.Utility.Helper.RequestStatus[1]"  hidden />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input  type="submit" class="btn btn-info w-75" value="Зареєструвати тур" />
                        </div>
                        <div class="col">
                            <a asp-controller="WorldMonument" asp-action="MonumentIndex" class="btn btn-danger w-75">Повернутися</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

WebMarathon/Views/Travel/TravelIndex.cshtml
@model IEnumerable<WebMarathon.Models.Travel>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Подорожі</h2>
        </div>
        @if (User.IsInRole(WebMarathon.Utility.Helper.Admin))
        {
            <div class="col-4 offset-8">
                <a asp-controller="Account" asp-action="Register" class="btn-info form-control text-center">Реєстрація нового користувача</a>
            </div>
        }
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Клієнт
                    </th>
                    <th>
                        Туристичний об'єкт
                    </th>
                    <th>
                        Дата подорожі
                    </th>
                    <th>
                        Статус заявки
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="25%">@item.User.UserName</td>
                        <td width="25%">@item.Monument.Name</td>
                        <td width="25%">@item.Date</td>
                        <td width="25%">@item.Status</td>
                        @if (User.IsInRole(WebMarathon.Utility.Helper.Admin) || User.IsInRole(WebMarathon.Utility.Helper.Operator))
                        {
                            <td width="25%">
                                <div class="w-100 btn-group" role="group">
                                    <a asp-controller="Travel" asp-action="TravelUpdate" asp-route-Id="@item.Id" class="btn btn-primary mx-1">Розглянути</a>
                                </div>
                            </td>
                        }
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>Не створено жодного туру</p>
    }

</div>

WebMarathon/Views/Travel/TravelUpdate.cshtml
@model WebMarathon.Models.Travel

<form method="post" asp-action="TravelUpdate">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-2">Огляд туру</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="MonumentId"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Date"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Status"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <select asp-for="MonumentId" asp-items="@ViewBag.TravelDropDown" disabled class="form-control"></select>
                    </div>
                    <div class="col-4">
                        <input asp-for="Date" readonly class="form-control" />
                    </div>
                    <div class="col-4">
                        <select asp-for="Status"
                                asp-items="@WebMarathon.Utility.Helper.GetRequestStatus()"
                                class="form-control">
                        </select>
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                </div>
                <br />
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Оновити" />
                        </div>
                        <div class="col">
                            <a asp-action="TravelIndex" class="btn btn-danger w-75">Повернутися</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="col-4">
        <select asp-for="MonumentId" asp-items="@ViewBag.TravelDropDown" hidden class="form-control"></select>
    </div>
</form>



@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}